/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.cafm.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
class FacilityWorkOrderClosureServiceTest{private final FacilityWorkOrderClosureService service=new FacilityWorkOrderClosureService();/**
                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                       */
@Test void closesCompleteOrder(){var r=service.assess(new FacilityWorkOrderClosureService.Request("W1",true,true,true,true,true,true,true,true));assertThat(r.decision()).isEqualTo(FacilityWorkOrderClosureService.Decision.CLOSE);}/**
                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                            */
@Test void blocksSafetyAndEvidenceGaps(){var r=service.assess(new FacilityWorkOrderClosureService.Request("W2",true,false,false,false,false,true,true,true));assertThat(r.blockers()).hasSize(4);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@Test void reviewsAcceptanceCostAndPrevention(){var r=service.assess(new FacilityWorkOrderClosureService.Request("W3",false,true,true,true,false,false,false,false));assertThat(r.actions()).hasSize(3);}}
